// Country list — no emoji flags (global enterprise app: text/ISO codes only).
// Each country has its own SEO-friendly slug used in the URL: /country/<slug>
export const COUNTRY_LIST = [
  { code: "VN", slug: "viet-nam", name: "Việt Nam" },
  { code: "US", slug: "hoa-ky", name: "Hoa Kỳ" },
  { code: "CN", slug: "trung-quoc", name: "Trung Quốc" },
  { code: "JP", slug: "nhat-ban", name: "Nhật Bản" },
  { code: "KR", slug: "han-quoc", name: "Hàn Quốc" },
  { code: "SG", slug: "singapore", name: "Singapore" },
  { code: "TH", slug: "thai-lan", name: "Thái Lan" },
  { code: "MY", slug: "malaysia", name: "Malaysia" },
  { code: "ID", slug: "indonesia", name: "Indonesia" },
  { code: "PH", slug: "philippines", name: "Philippines" },
  { code: "IN", slug: "an-do", name: "Ấn Độ" },
  { code: "AU", slug: "uc", name: "Úc" },
  { code: "GB", slug: "vuong-quoc-anh", name: "Vương quốc Anh" },
  { code: "DE", slug: "duc", name: "Đức" },
  { code: "FR", slug: "phap", name: "Pháp" },
  { code: "IT", slug: "y", name: "Ý" },
  { code: "ES", slug: "tay-ban-nha", name: "Tây Ban Nha" },
  { code: "NL", slug: "ha-lan", name: "Hà Lan" },
  { code: "CA", slug: "canada", name: "Canada" },
  { code: "MX", slug: "mexico", name: "Mexico" },
  { code: "BR", slug: "brazil", name: "Brazil" },
  { code: "AR", slug: "argentina", name: "Argentina" },
  { code: "AE", slug: "uae", name: "UAE" },
  { code: "SA", slug: "a-rap-saudi", name: "Ả Rập Saudi" },
  { code: "ZA", slug: "nam-phi", name: "Nam Phi" },
  { code: "EG", slug: "ai-cap", name: "Ai Cập" },
  { code: "TR", slug: "tho-nhi-ky", name: "Thổ Nhĩ Kỳ" },
  { code: "RU", slug: "nga", name: "Nga" },
  { code: "CH", slug: "thuy-si", name: "Thụy Sĩ" },
  { code: "SE", slug: "thuy-dien", name: "Thụy Điển" },
];

export const INDUSTRY_LIST = [
  { slug: "technology", name: "Công nghệ thông tin" },
  { slug: "finance", name: "Tài chính - Ngân hàng" },
  { slug: "real-estate", name: "Bất động sản" },
  { slug: "manufacturing", name: "Sản xuất" },
  { slug: "retail", name: "Thương mại - Bán lẻ" },
  { slug: "hospitality", name: "Du lịch - Khách sạn" },
  { slug: "education", name: "Giáo dục" },
  { slug: "healthcare", name: "Y tế - Sức khỏe" },
  { slug: "food-beverage", name: "Thực phẩm & Đồ uống" },
  { slug: "logistics", name: "Logistics - Vận tải" },
  { slug: "agriculture", name: "Nông nghiệp" },
  { slug: "energy", name: "Năng lượng" },
  { slug: "marketing", name: "Truyền thông - Marketing" },
  { slug: "consulting", name: "Tư vấn - Pháp lý" },
  { slug: "construction", name: "Xây dựng" },
  { slug: "fashion", name: "Thời trang - Làm đẹp" },
  { slug: "entertainment", name: "Giải trí - Nghệ thuật" },
  { slug: "automotive", name: "Ô tô - Xe máy" },
  { slug: "other", name: "Khác" },
];
