// Country list — no emoji flags (global enterprise app: text/ISO codes only).
export const COUNTRY_LIST = [
  { code: "VN", name: "Việt Nam" }, { code: "US", name: "Hoa Kỳ" },
  { code: "CN", name: "Trung Quốc" }, { code: "JP", name: "Nhật Bản" },
  { code: "KR", name: "Hàn Quốc" }, { code: "SG", name: "Singapore" },
  { code: "TH", name: "Thái Lan" }, { code: "MY", name: "Malaysia" },
  { code: "ID", name: "Indonesia" }, { code: "PH", name: "Philippines" },
  { code: "IN", name: "Ấn Độ" }, { code: "AU", name: "Úc" },
  { code: "GB", name: "Vương quốc Anh" }, { code: "DE", name: "Đức" },
  { code: "FR", name: "Pháp" }, { code: "IT", name: "Ý" },
  { code: "ES", name: "Tây Ban Nha" }, { code: "NL", name: "Hà Lan" },
  { code: "CA", name: "Canada" }, { code: "MX", name: "Mexico" },
  { code: "BR", name: "Brazil" }, { code: "AR", name: "Argentina" },
  { code: "AE", name: "UAE" }, { code: "SA", name: "Ả Rập Saudi" },
  { code: "ZA", name: "Nam Phi" }, { code: "EG", name: "Ai Cập" },
  { code: "TR", name: "Thổ Nhĩ Kỳ" }, { code: "RU", name: "Nga" },
  { code: "CH", name: "Thụy Sĩ" }, { code: "SE", name: "Thụy Điển" },
];

export const INDUSTRY_LIST = [
  { slug: "technology", name: "Công nghệ thông tin" },
  { slug: "finance", name: "Tài chính - Ngân hàng" },
  { slug: "real-estate", name: "Bất động sản" },
  { slug: "manufacturing", name: "Sản xuất" },
  { slug: "retail", name: "Thương mại - Bán lẻ" },
  { slug: "hospitality", name: "Du lịch - Khách sạn" },
  { slug: "education", name: "Giáo dục" },
  { slug: "healthcare", name: "Y tế - Sức khỏe" },
  { slug: "food-beverage", name: "Thực phẩm & Đồ uống" },
  { slug: "logistics", name: "Logistics - Vận tải" },
  { slug: "agriculture", name: "Nông nghiệp" },
  { slug: "energy", name: "Năng lượng" },
  { slug: "marketing", name: "Truyền thông - Marketing" },
  { slug: "consulting", name: "Tư vấn - Pháp lý" },
  { slug: "construction", name: "Xây dựng" },
  { slug: "fashion", name: "Thời trang - Làm đẹp" },
  { slug: "entertainment", name: "Giải trí - Nghệ thuật" },
  { slug: "automotive", name: "Ô tô - Xe máy" },
  { slug: "other", name: "Khác" },
];
