export const COUNTRY_LIST = [
  { code: "VN", name: "Việt Nam", flag: "🇻🇳" }, { code: "US", name: "Hoa Kỳ", flag: "🇺🇸" },
  { code: "CN", name: "Trung Quốc", flag: "🇨🇳" }, { code: "JP", name: "Nhật Bản", flag: "🇯🇵" },
  { code: "KR", name: "Hàn Quốc", flag: "🇰🇷" }, { code: "SG", name: "Singapore", flag: "🇸🇬" },
  { code: "TH", name: "Thái Lan", flag: "🇹🇭" }, { code: "MY", name: "Malaysia", flag: "🇲🇾" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩" }, { code: "PH", name: "Philippines", flag: "🇵🇭" },
  { code: "IN", name: "Ấn Độ", flag: "🇮🇳" }, { code: "AU", name: "Úc", flag: "🇦🇺" },
  { code: "GB", name: "Vương quốc Anh", flag: "🇬🇧" }, { code: "DE", name: "Đức", flag: "🇩🇪" },
  { code: "FR", name: "Pháp", flag: "🇫🇷" }, { code: "IT", name: "Ý", flag: "🇮🇹" },
  { code: "ES", name: "Tây Ban Nha", flag: "🇪🇸" }, { code: "NL", name: "Hà Lan", flag: "🇳🇱" },
  { code: "CA", name: "Canada", flag: "🇨🇦" }, { code: "MX", name: "Mexico", flag: "🇲🇽" },
  { code: "BR", name: "Brazil", flag: "🇧🇷" }, { code: "AR", name: "Argentina", flag: "🇦🇷" },
  { code: "AE", name: "UAE", flag: "🇦🇪" }, { code: "SA", name: "Ả Rập Saudi", flag: "🇸🇦" },
  { code: "ZA", name: "Nam Phi", flag: "🇿🇦" }, { code: "EG", name: "Ai Cập", flag: "🇪🇬" },
  { code: "TR", name: "Thổ Nhĩ Kỳ", flag: "🇹🇷" }, { code: "RU", name: "Nga", flag: "🇷🇺" },
  { code: "CH", name: "Thụy Sĩ", flag: "🇨🇭" }, { code: "SE", name: "Thụy Điển", flag: "🇸🇪" },
];

export const INDUSTRY_LIST = [
  { slug: "technology", name: "Công nghệ thông tin" },
  { slug: "finance", name: "Tài chính - Ngân hàng" },
  { slug: "real-estate", name: "Bất động sản" },
  { slug: "manufacturing", name: "Sản xuất" },
  { slug: "retail", name: "Thương mại - Bán lẻ" },
  { slug: "hospitality", name: "Du lịch - Khách sạn" },
  { slug: "education", name: "Giáo dục" },
  { slug: "healthcare", name: "Y tế - Sức khỏe" },
  { slug: "food-beverage", name: "Thực phẩm & Đồ uống" },
  { slug: "logistics", name: "Logistics - Vận tải" },
  { slug: "agriculture", name: "Nông nghiệp" },
  { slug: "energy", name: "Năng lượng" },
  { slug: "marketing", name: "Truyền thông - Marketing" },
  { slug: "consulting", name: "Tư vấn - Pháp lý" },
  { slug: "construction", name: "Xây dựng" },
  { slug: "fashion", name: "Thời trang - Làm đẹp" },
  { slug: "entertainment", name: "Giải trí - Nghệ thuật" },
  { slug: "automotive", name: "Ô tô - Xe máy" },
  { slug: "other", name: "Khác" },
];
