/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as CountrySlugRouteImport } from './routes/country.$slug'
import { Route as BusinessStatsRouteImport } from './routes/business.stats'
import { Route as BusinessEditRouteImport } from './routes/business.edit'
import { Route as BlogHowToFindInternationalB2bPartnersRouteImport } from './routes/blog.how-to-find-international-b2b-partners'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as PrintTypeSlugRouteImport } from './routes/print.$type.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountrySlugRoute = CountrySlugRouteImport.update({
  id: '/country/$slug',
  path: '/country/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessStatsRoute = BusinessStatsRouteImport.update({
  id: '/business/stats',
  path: '/business/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessEditRoute = BusinessEditRouteImport.update({
  id: '/business/edit',
  path: '/business/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToFindInternationalB2bPartnersRoute =
  BlogHowToFindInternationalB2bPartnersRouteImport.update({
    id: '/blog/how-to-find-international-b2b-partners',
    path: '/blog/how-to-find-international-b2b-partners',
    getParentRoute: () => rootRouteImport,
  } as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintTypeSlugRoute = PrintTypeSlugRouteImport.update({
  id: '/print/$type/$slug',
  path: '/print/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contacts': typeof ContactsRoute
  '/countries': typeof CountriesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/b/$slug': typeof BSlugRoute
  '/blog/how-to-find-international-b2b-partners': typeof BlogHowToFindInternationalB2bPartnersRoute
  '/business/edit': typeof BusinessEditRoute
  '/business/stats': typeof BusinessStatsRoute
  '/country/$slug': typeof CountrySlugRoute
  '/p/$slug': typeof PSlugRoute
  '/print/$type/$slug': typeof PrintTypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contacts': typeof ContactsRoute
  '/countries': typeof CountriesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/b/$slug': typeof BSlugRoute
  '/blog/how-to-find-international-b2b-partners': typeof BlogHowToFindInternationalB2bPartnersRoute
  '/business/edit': typeof BusinessEditRoute
  '/business/stats': typeof BusinessStatsRoute
  '/country/$slug': typeof CountrySlugRoute
  '/p/$slug': typeof PSlugRoute
  '/print/$type/$slug': typeof PrintTypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contacts': typeof ContactsRoute
  '/countries': typeof CountriesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/b/$slug': typeof BSlugRoute
  '/blog/how-to-find-international-b2b-partners': typeof BlogHowToFindInternationalB2bPartnersRoute
  '/business/edit': typeof BusinessEditRoute
  '/business/stats': typeof BusinessStatsRoute
  '/country/$slug': typeof CountrySlugRoute
  '/p/$slug': typeof PSlugRoute
  '/print/$type/$slug': typeof PrintTypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contacts'
    | '/countries'
    | '/dashboard'
    | '/explore'
    | '/following'
    | '/inbox'
    | '/leads'
    | '/login'
    | '/me'
    | '/pricing'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/b/$slug'
    | '/blog/how-to-find-international-b2b-partners'
    | '/business/edit'
    | '/business/stats'
    | '/country/$slug'
    | '/p/$slug'
    | '/print/$type/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contacts'
    | '/countries'
    | '/dashboard'
    | '/explore'
    | '/following'
    | '/inbox'
    | '/leads'
    | '/login'
    | '/me'
    | '/pricing'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/b/$slug'
    | '/blog/how-to-find-international-b2b-partners'
    | '/business/edit'
    | '/business/stats'
    | '/country/$slug'
    | '/p/$slug'
    | '/print/$type/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contacts'
    | '/countries'
    | '/dashboard'
    | '/explore'
    | '/following'
    | '/inbox'
    | '/leads'
    | '/login'
    | '/me'
    | '/pricing'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/b/$slug'
    | '/blog/how-to-find-international-b2b-partners'
    | '/business/edit'
    | '/business/stats'
    | '/country/$slug'
    | '/p/$slug'
    | '/print/$type/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactsRoute: typeof ContactsRoute
  CountriesRoute: typeof CountriesRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  FollowingRoute: typeof FollowingRoute
  InboxRoute: typeof InboxRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BSlugRoute: typeof BSlugRoute
  BlogHowToFindInternationalB2bPartnersRoute: typeof BlogHowToFindInternationalB2bPartnersRoute
  BusinessEditRoute: typeof BusinessEditRoute
  BusinessStatsRoute: typeof BusinessStatsRoute
  CountrySlugRoute: typeof CountrySlugRoute
  PSlugRoute: typeof PSlugRoute
  PrintTypeSlugRoute: typeof PrintTypeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$slug': {
      id: '/country/$slug'
      path: '/country/$slug'
      fullPath: '/country/$slug'
      preLoaderRoute: typeof CountrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/stats': {
      id: '/business/stats'
      path: '/business/stats'
      fullPath: '/business/stats'
      preLoaderRoute: typeof BusinessStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/edit': {
      id: '/business/edit'
      path: '/business/edit'
      fullPath: '/business/edit'
      preLoaderRoute: typeof BusinessEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-find-international-b2b-partners': {
      id: '/blog/how-to-find-international-b2b-partners'
      path: '/blog/how-to-find-international-b2b-partners'
      fullPath: '/blog/how-to-find-international-b2b-partners'
      preLoaderRoute: typeof BlogHowToFindInternationalB2bPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$type/$slug': {
      id: '/print/$type/$slug'
      path: '/print/$type/$slug'
      fullPath: '/print/$type/$slug'
      preLoaderRoute: typeof PrintTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactsRoute: ContactsRoute,
  CountriesRoute: CountriesRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  FollowingRoute: FollowingRoute,
  InboxRoute: InboxRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BSlugRoute: BSlugRoute,
  BlogHowToFindInternationalB2bPartnersRoute:
    BlogHowToFindInternationalB2bPartnersRoute,
  BusinessEditRoute: BusinessEditRoute,
  BusinessStatsRoute: BusinessStatsRoute,
  CountrySlugRoute: CountrySlugRoute,
  PSlugRoute: PSlugRoute,
  PrintTypeSlugRoute: PrintTypeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
